spring.application.name=restaurante
# Configuração do banco de dados     endereço local
spring.datasource.url=jdbc:mysql://localhost:3306/projetorestaurante
spring.datasource.username=root
spring.datasource.password=root123

# Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 #dependencia que sabe conversar com o mysql
# Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
#ajudara na criação das tabelas ao usar o entity

# Mostrar SQL no terminal
spring.jpa.show-sql=true
